#!/bin/bash
# blacklist old driver and unload
echo "blacklist silead" | sudo tee /etc/modprobe.d/blacklist-silead.conf
sudo rmmod silead

# copy firmware silead_ts.fw
sudo cp /silead_ts.fw /lib/firmware/

# install new driver
pacman -Syu git make gcc dkms
cd gslx680-acpi-master
MODULE_VER=$(grep VERSION dkms.conf |  awk -F '"' '{print $2}')
sudo mkdir /usr/src/gslx680-acpi-$MODULE_VER
sudo cp -r * /usr/src/gslx680-acpi-$MODULE_VER/
sudo dkms add gslx680-acpi/$MODULE_VER
sudo dkms install gslx680-acpi/$MODULE_VER

#check touchscreen
sudo modprobe gslx680_ts_acpi

# copy bcm driver
sudo mkdir -p /lib/firmware/brcm
sudo cp -n /brcmfmac43430a0-sdio.bin /lib/firmware/brcm
sudo cp -n /brcmfmac43430a0-sdio.Insyde-BayTrail.txt /lib/firmware/brcm
sudo cp -n /brcmfmac43430a0-sdio.txt /lib/firmware/brcm
sudo cp -n /BCM4343A0.hcd /lib/firmware/brcm


echo "All done"
